# configuration for robot motion
map_name: 4
robot:
  battery_capacity: 5.0
  energy_consumption: 6.0
sensor:
  time_to_wait: 4.0
  energy_consuption: 5.0
  range: 5.0
key_points:
  -(4, 5)
  -(4, 6)
