# configuration for robot motion
map_name: map_cleaned.pgm
robot:
  battery_capacity: 1000000.0
  energy_consumption: 0.001
  charge_locale: [250,125]
sensor:
  time_to_wait: 5.0
  energy_consuption: 0.0002
  range: 2.0
key_points:
  - [130, 80]
  - [90, 140]
  - [130, 160]
