# configuration for robot motion
map_locale: map_grid.txt
robot:
  battery_capacity: 5.0
  energy_consumption: 6.0
  charge_location: (2, 3)
sensor:
  time_to_wait: 5.0
  energy_consuption: 6.0
  range: 5.0
key_points:
  - (4, 5)
