# configuration for robot motion
map_locale: OIP_grid.txt
robot:
  battery_capacity: 4.0
  energy_consumption: 4.0
  charge_location: (4, 5)
sensor:
  time_to_wait: 5.0
  energy_consuption: 5.0
  range: 5.0
key_points:
